name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/bicep.yaml'
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  
